### ISSUE TITLE
Apply Decidim GEO bugfix

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#432]
Currently, dedicim Geo displays maps everywhere, even then when no geolocated data is present.

This currently blocks our deployment

As soon as octree has the bugfix, please install it on our side. 

@froger: Have you got any updates on this?

**Comment by larsUE** [comment]
Update 0.2.2. has the bugfix! Thanks a lot.

**Comment by Robin481** [comment]
@larsUE 
There seems to be an issue with `v0.2.2.` 
I am following the installation guide, after upgrading the gem one should execute `bundle exec rails decidim_geo:install:migrations`.
This doesn't work at the moment, it looks like some required files are not there. 

I've spoken to @Kagemaru and he told me that we don't have a time budget for this, so we should just reconcile with you. 

Do you want to pass this back to the decidim_geo team?  

```
❯ bundle exec rails decidim_geo:install:migrations
rails aborted!
LoadError: cannot load such file -- decidim/decidim_geo/api
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/dependencies.rb:332:in `block in require'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/dependencies.rb:332:in `require'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/bundler/gems/decidim-module-geo-fdfc76e0588a/lib/decidim/decidim_geo.rb:6:in `<main>'
/home/rsteiner/code/decidim-zuerich/config/application.rb:15:in `<main>'
/home/rsteiner/code/decidim-zuerich/Rakefile:4:in `require_relative'
/home/rsteiner/code/decidim-zuerich/Rakefile:4:in `<main>'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.7/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.7/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.7/lib/rails/command.rb:50:in `invoke'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.7/lib/rails/commands.rb:18:in `<main>'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'

Caused by:
LoadError: cannot load such file -- decidim-decidim_geo
/home/rsteiner/code/decidim-zuerich/config/application.rb:15:in `<main>'
/home/rsteiner/code/decidim-zuerich/Rakefile:4:in `require_relative'
/home/rsteiner/code/decidim-zuerich/Rakefile:4:in `<main>'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.7/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.7/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.7/lib/rails/command.rb:50:in `invoke'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.7/lib/rails/commands.rb:18:in `<main>'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/rsteiner/code/decidim-zuerich/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

**Comment by froger** [comment]
Hi, @Robin481 
I can make a PR today on your repo to fix the issue, you can assign me the issue for now if it's fine for you.

**Comment by larsUE** [comment]
@froger do you have an update on the issue?

**Comment by nicolefreypuzzle** [comment]
PR wird heute eingespielt

**Comment by froger** [comment]
Hello @nicolefreypuzzle I've done a PR there: https://github.com/puzzle/decidim-zuerich/pull/439

**Comment by nicolefreypuzzle** [comment]
@Kagemaru Go for it :-)
